version: 2

project_name: remembery

builds:
  - id: remembery
    main: .
    binary: remembery
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: raw
    ids: [remembery]
    formats: [binary]
    name_template: >-
      {{ .Binary }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}arm64
      {{- else }}{{ .Arch }}{{ end }}

  - id: pkg
    ids: [remembery]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}arm64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: "checksums.txt"

changelog:
  disable: true

homebrew_casks:
  - repository:
      owner: alankiri
      name: homebrew-tap
      token: "{{ .Env.GORELEASER_GITHUB_PERSONAL_ACCESS_TOKEN }}"
    ids: [pkg]
    homepage: "https://github.com/alankiri/remembery"
    description: "A small TUI for memorizing strings"
    license: "MIT"
    binaries:
      - remembery

scoops:
  - repository:
      owner: alankiri
      name: scoop-bucket
      token: "{{ .Env.GORELEASER_GITHUB_PERSONAL_ACCESS_TOKEN }}"
    ids: [pkg]
    homepage: "https://github.com/alankiri/remembery"
    description: "A small TUI for memorizing strings"
    license: "MIT"

snapcrafts:
  - ids: [remembery]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    title: remembery
    summary: "A small TUI for memorizing strings"
    description: |
      Remembery is a TUI for helping you memorize passwords,
      phone numbers, important IDs, and any other string.
    grade: stable
    confinement: classic
    base: core22
    license: MIT
    publish: false
    apps:
      remembery:
        command: remembery
