package levels

var Default = []Level{
	{
		Number:                     1,
		Color:                      "63",
		RepetitionCount:            3,
		InterAttemptDelay:          60,
		BaseBlurPercent:            0,
		BlurStepPercent:            15,
		MaxBlurPercent:             45,
		HintReductionPercent:       50,
		RequiredSessionsToProgress: 3,
		SessionIntervalDays:        1,
		TypingValidationMode:       "allow_highlight",
		Description:                "Full reveal — light blur to build comfort.",
	},
	{
		Number:                     2,
		Color:                      "121",
		RepetitionCount:            4,
		InterAttemptDelay:          30,
		BaseBlurPercent:            20,
		BlurStepPercent:            15,
		MaxBlurPercent:             55,
		HintReductionPercent:       60,
		RequiredSessionsToProgress: 4,
		SessionIntervalDays:        1,
		TypingValidationMode:       "allow_highlight",
		Description:                "Light blur, most characters still visible.",
	},
	{
		Number:                     3,
		Color:                      "226",
		RepetitionCount:            5,
		InterAttemptDelay:          30,
		BaseBlurPercent:            40,
		BlurStepPercent:            10,
		MaxBlurPercent:             65,
		HintReductionPercent:       70,
		RequiredSessionsToProgress: 2,
		SessionIntervalDays:        2,
		TypingValidationMode:       "allow_highlight",
		Description:                "Moderate blur; you need to recall more.",
	},
	{
		Number:                     4,
		Color:                      "208",
		RepetitionCount:            5,
		InterAttemptDelay:          30,
		BaseBlurPercent:            55,
		BlurStepPercent:            10,
		MaxBlurPercent:             75,
		HintReductionPercent:       80,
		RequiredSessionsToProgress: 3,
		SessionIntervalDays:        2,
		TypingValidationMode:       "allow_highlight",
		Description:                "Heavy blur; only a few characters shown.",
	},
	{
		Number:                     5,
		Color:                      "196",
		RepetitionCount:            6,
		InterAttemptDelay:          30,
		BaseBlurPercent:            70,
		BlurStepPercent:            5,
		MaxBlurPercent:             85,
		HintReductionPercent:       90,
		RequiredSessionsToProgress: 3,
		SessionIntervalDays:        3,
		TypingValidationMode:       "allow_highlight",
		Description:                "Near-full blur, but one character stays visible.",
	},
}
