package levels

var Default = []Level{
	{
		Number:                     1,
		Color:                      "63",
		RepetitionCount:            3,
		InterAttemptDelay:          1,
		BaseBlurPercent:            0,
		BlurStepPercent:            15,
		MaxBlurPercent:             45,
		RequiredSessionsToProgress: 3,
		SessionIntervalHours:       24,
		Description:                "Full reveal — light blur to build comfort.",
	},
	{
		Number:                     2,
		Color:                      "121",
		RepetitionCount:            4,
		InterAttemptDelay:          1,
		BaseBlurPercent:            20,
		BlurStepPercent:            15,
		MaxBlurPercent:             55,
		RequiredSessionsToProgress: 4,
		SessionIntervalHours:       24,
		Description:                "Light blur, most characters still visible.",
	},
	{
		Number:                     3,
		Color:                      "226",
		RepetitionCount:            5,
		InterAttemptDelay:          1,
		BaseBlurPercent:            40,
		BlurStepPercent:            10,
		MaxBlurPercent:             65,
		RequiredSessionsToProgress: 2,
		SessionIntervalHours:       48,
		Description:                "Moderate blur; you need to recall more.",
	},
	{
		Number:                     4,
		Color:                      "208",
		RepetitionCount:            5,
		InterAttemptDelay:          1,
		BaseBlurPercent:            55,
		BlurStepPercent:            10,
		MaxBlurPercent:             75,
		RequiredSessionsToProgress: 3,
		SessionIntervalHours:       48,
		Description:                "Heavy blur; only a few characters shown.",
	},
	{
		Number:                     5,
		Color:                      "196",
		RepetitionCount:            6,
		InterAttemptDelay:          1,
		BaseBlurPercent:            70,
		BlurStepPercent:            5,
		MaxBlurPercent:             85,
		RequiredSessionsToProgress: 3,
		SessionIntervalHours:       72,
		Description:                "Near-full blur, but one character stays visible.",
	},
}
